Feature 1 to main
leooruiz/Marvel_app pull request #1
Opened 2024-02-23 03:48 UTC by leooruiz

2024-02-28 12:15 UTC, gabrieluca commented
Para futuros projetos, utilizar o nome do repo todo minúsculo.
(Não alterar esse senão gerará conflitos)

2024-03-02 15:39 UTC, gabrieluca requested changes
Review enviado!

Obs.: ^ significa um comentário repetido

2024-03-02 15:39 UTC, gabrieluca commented on pubspec.yaml
> +  shared_preferences:
Para conhecimento, em `environment` pode-se adicionar (opcional) uma versão mínima do Flutter também (do Dart está definido já em `sdk`), por exemplo:

```yaml
environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.9 <4.0.0"
```

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/api_service/data_api.dart
> +  }
Num app com múltiplos endpoints, o ideal seria isso aqui:
```suggestion
  void configureDio() {
    dio.options = BaseOptions(
      baseUrl: 'https://gateway.marvel.com/v1/public/',
      queryParameters: {
        'ts': '123',
        'apikey': '044479a19929992d86c53efb86add0a5',
        'hash': 'd7d2e2160357184800ff55f0b845be50',
      },
      connectTimeout: const Duration(seconds: 5),
      receiveTimeout: const Duration(seconds: 5),
    );
  }
```

Pois essas infos servirão para todos os endpoints.
Aí na chamada do endpoint em específico, seria `dio.get(characters)`

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/theme_bloc/theme_states.dart
> +  bool isLight;
O parâmetro isLight é desnecessário, pois é só validar se o state é  ThemeDarkState ou ThemeLightState

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/home.dart
> +                        _light, //TODO: Salvar preferencia do usuario no shared prefs
Essa variável não é necessária, como você já está usando o `ThemeBloc`, é só chamar state is `ThemeLightState`

2024-03-02 15:39 UTC, gabrieluca commented on lib/utils/constants/wordings.dart
> +class Wordings {
Essa classe pode ser abstrata, para nunca ser instanciada.

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/theme_bloc/theme_bloc.dart
> +    }
Quando for chamar o SharedPref para salvar o tema, executar neste método

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/home.dart
> +          backgroundColor: const Color.fromARGB(255, 114, 24, 24),
Criar uma classe de cores semelhante a classe de  `Wordings`, contendo todas as cores usadas no projeto.

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/home.dart
> +    final themeBloc = context.watch<ThemeBloc>();
Se não é usado o estado, chamar `context.read`

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/theme_bloc/theme_bloc.dart
> +      (event, emit) => changeTheme(emit, event),
Pode-se usar o tear-off nesta linha, escrevendo apenas `changeTheme` (https://dart.dev/tools/linter-rules/unnecessary_lambdas)

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/components/heroes_list.dart
> +class HeroesList extends StatelessWidget {
Renomear para `HeroesListScreen` ou `HeroesListPage`

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/components/heroes_list.dart
> +          } else {
Esse `else` nunca ocorrerá

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/components/heroes_list.dart
> +                return HeroCard(heroes: state.heroes, index: index);
Passar `state.heroes[index]` no lugar da lista

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/components/hero_card.dart
> +          height: 125,
O ideal é definir a altura da imagem, e deixar o card "solto", assim se a altura do texto for maior 125, não dá overflow.
No atual design está ok, mas só para ficar de orientação para o futuro.

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/theme_bloc/theme_bloc.dart
> +    if (event.isLight) {
Sempre tipe os parâmetros:
```suggestion
  void changeTheme(ThemeChangeEvent event, Emitter<ThemeStates> emit) {
```

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/components/heroes_list.dart
> +            return SliverFillRemaining(
Como você está usando `return` (guard clause) , o else é desnecessário (https://refactoring.guru/pt-br/replace-nested-conditional-with-guard-clauses)

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/home_bloc/home_bloc.dart
> +  void getHeroes(emit) async {
Tipar parâmetros

2024-03-02 15:39 UTC, gabrieluca commented on lib/controllers/heroes_controller.dart
> +class HeroesController {
Renomear classe para `HeroesRepository` e mover para dentro de `data` (https://codewithandrea.com/articles/flutter-repository-pattern/)

2024-03-02 15:39 UTC, gabrieluca commented on lib/controllers/heroes_controller.dart
> +  final List<MarvelHero> favoriteHeroes = [];
O estado da aplicação deve estar somente dentro do Bloc State ou no widget

2024-03-02 15:39 UTC, gabrieluca commented on lib/controllers/heroes_controller.dart
> +    homeHeroes.addAll(heroesFromApi);
Remover método, ele não é necessário para agora

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/api_service/data_api.dart
> +      final List<MarvelHero> heroes = List<MarvelHero>.from(
`List<MarvelHero>.from(` é desnecessário

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/details.dart
> +class Details extends StatefulWidget {
Converter para `Stateless`

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/details.dart
> +    final bloc = context.watch<FavoritesBloc>();
Se não é usado o estado, chamar context.read

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/favorites.dart
> +class Favorites extends StatelessWidget {
`FavoritesScreen`

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/favorites.dart
> +              return SliverList.builder(
Exibir um widget para quando a lista for vazia

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/favorites.dart
> +              return SliverToBoxAdapter(child: Text(state.errorMessage));
Melhorar design do estado de erro

2024-03-02 15:39 UTC, gabrieluca commented on lib/screens/favorites.dart
> +            } else {
Nunca executará esse `else`

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/favorite_bloc/favorites_bloc.dart
> +  void getHeroes(emit) async {
Declarar método depois do construtor e tipar parâmetro

2024-03-02 15:39 UTC, gabrieluca commented on lib/domain/business/bloc/favorite_bloc/favorites_bloc.dart
> +    void removeHero(emit, event) async {
Mover métodos para fora do construtor

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +    }
Qual o motivo desse `if`?

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +    final String? currentHero = prefs.getString(hero.name);
Não é preciso salvar o Hero individualmente, só adicionar na lista

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +      listaPrefs.add(currentHero);
Adicionar diretamente `hero.toJson()`

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +    }
^

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +    }
^

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +    if (!listaPrefs!.contains(currentHero!)) {
Validar se `listaPrefs` é null

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +    return favoritesDatabase!;
Enviar lista vazia se null

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +  }
Adicionar método direto em `MarvelHero` ao invés disso
Ex:
`Map<String, dynamic> fromJson(String source) => json.decode(source);`

2024-03-02 15:39 UTC, gabrieluca commented on lib/data/dao_service/shared_prefs.dart
> +  MarvelHero _fromMapToHero(Map<String, dynamic> map) {
Remover método e utilizar `MarvelHero.fromMap`

2024-03-06 14:18 UTC, leooruiz commented on lib/domain/business/bloc/theme_bloc/theme_bloc.dart
> +      (event, emit) => changeTheme(emit, event),
Na realidade ele não funciona se eu utilizo o tear-off aqui.

2024-03-06 14:42 UTC, leooruiz commented on lib/screens/home.dart
> +          backgroundColor: const Color.fromARGB(255, 114, 24, 24),
Vou fazer isso em um arquivo de themes pode ser? Você mesmo disse que era até melhor.

2024-03-06 18:44 UTC, gabrieluca requested changes

2024-03-06 18:44 UTC, gabrieluca commented on lib/domain/business/bloc/favorite_bloc/favorites_bloc.dart
> +      (event, emit) => removeHero(emit, event),
Substituir linha por `removeHero` (tear-off)

2024-03-06 18:44 UTC, gabrieluca commented on lib/domain/business/bloc/favorite_bloc/favorites_bloc.dart
> +    FavoriteRemoveEvent event,
Inverter ordem dos parâmetros para bater com o construtor do Bloc `(event, emit)`

2024-03-06 18:44 UTC, gabrieluca commented on lib/domain/business/bloc/theme_bloc/theme_bloc.dart
> +      (event, emit) => changeTheme(emit, event),
VOc6e precisa inverter a ordem dos parâmetros na declaração do método
```dart
void changeTheme(ThemeChangeEvent event, Emitter<ThemeStates> emit) {
```

2024-03-06 18:44 UTC, gabrieluca commented on pubspec.yaml
> +  bloc:
Declarar uma versão mínima específica do bloc

2024-03-06 18:44 UTC, gabrieluca commented on pubspec.yaml
> +  dio:
Sempre declarar uma versão mínima

2024-03-06 18:44 UTC, gabrieluca commented on lib/screens/home.dart
> +                            false, //TODO: Salvar preferencia do usuario no shared prefs
Qual o objetivo desse `|| false` ?

2024-03-06 18:44 UTC, gabrieluca commented on lib/screens/details.dart
> +    final bloc = context.watch<FavoritesBloc>();
Ok

2024-03-08 13:54 UTC, leooruiz commented on pubspec.yaml
> +  bloc:
Como eu sei qual a versão mínima que devo colocar?

2024-03-18 17:24 UTC, merged